spring.application.name=homes-app
spring.datasource.url=jdbc:postgresql://localhost:5432/homes_app
# Change to 'update' if Hibernate is to automatically create/update the database schema based on new/changed entities
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false